# see http://mobile.tutsplus.com/tutorials/android/ndk-tutorial/

LOCAL_PATH := $(call my-dir)

SRC_MAIN_DIR := android-database-sqlcipher/android-database-sqlcipher/src/main

include $(CLEAR_VARS)

SQLCIPHER_DIR := $(SRC_MAIN_DIR)/external/sqlcipher

LOCAL_C_INCLUDES := $(SQLCIPHER_DIR) $(SRC_MAIN_DIR)
LOCAL_LDLIBS := -llog -latomic
LOCAL_LDFLAGS += -L../$(SRC_MAIN_DIR)/external/android-libs/$(TARGET_ARCH_ABI) -fuse-ld=bfd
LOCAL_STATIC_LIBRARIES += static-libcrypto
LOCAL_LDLIBS := -llog
LOCAL_CFLAGS += -DSQLITE_HAS_CODEC
LOCAL_CFLAGS += -DSQLITE_SOUNDEX
LOCAL_CFLAGS += -DHAVE_USLEEP=1
LOCAL_CFLAGS += -DSQLITE_TEMP_STORE=3
LOCAL_CFLAGS += -DSQLITE_THREADSAFE=1
LOCAL_CFLAGS += -DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576
LOCAL_CFLAGS += -DNDEBUG=1
LOCAL_CFLAGS += -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1
LOCAL_CFLAGS += -DSQLITE_ENABLE_LOAD_EXTENSION
LOCAL_CFLAGS += -DSQLITE_ENABLE_COLUMN_METADATA
LOCAL_CFLAGS += -DSQLITE_ENABLE_UNLOCK_NOTIFY
LOCAL_CFLAGS += -DSQLITE_ENABLE_RTREE
LOCAL_CFLAGS += -DSQLITE_ENABLE_STAT3
LOCAL_CFLAGS += -DSQLITE_ENABLE_STAT4
LOCAL_CFLAGS += -DSQLITE_ENABLE_JSON1
LOCAL_CFLAGS += -DSQLITE_ENABLE_FTS3_PARENTHESIS
LOCAL_CFLAGS += -DSQLITE_ENABLE_FTS4
LOCAL_CFLAGS += -DSQLITE_ENABLE_FTS5
LOCAL_CFLAGS += -DSQLCIPHER_CRYPTO_OPENSSL
LOCAL_CFLAGS += -DSQLITE_DISABLE_LFS
LOCAL_MODULE := sqlite-native-driver
LOCAL_SRC_FILES := ../$(SQLCIPHER_DIR)/sqlite3.c \
    ../sqlite-rapidjson/sqlite-rapidjson.cpp

include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := static-libcrypto
LOCAL_EXPORT_C_INCLUDES := $(SRC_MAIN_DIR)/external/openssl/include
LOCAL_SRC_FILES := ../$(SRC_MAIN_DIR)/external/android-libs/$(TARGET_ARCH_ABI)/libcrypto.a
include $(PREBUILT_STATIC_LIBRARY)
